/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: b2a7c2d0f9a349be68143002e31e596d)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		R2: R2Bucket;
		TRANSCRIPTION_QUEUE: Queue;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
